name: NuggetMC-Core
main: net.nuggetmc.core.Main
version: 2.0
commands:
   debug:
      description: A command used to inject code when debugging.
      usage: /debug
permissions:
  nmc.*:
    description: Blank description.
    children:
      nmc.debug: true
  nmc.debug:
    description: A command used to inject code when debugging.
    default: op