name: NuggetMC-Core
main: net.nuggetmc.core.Main
version: 2.0
commands:
  debug:
    description: A command used to inject code when debugging.
    permission: nmc.rank
    usage: /debug
  ghead:
    description: Gives a player a Golden Head.
    usage: /ghead <player>
    permission: nmc.ghead
  head:
    description: Gives a player a player's head.
    usage: /head <player> <player>
    permission: nmc.head
  invconvert:
    description: A developer tool to serialize player inventories.
    usage: /invconvert <get/set> <file> (path)
    permission: nmc.ic
    aliases: [ic]
  nuggetmc:
    description: The plugin-hook configuration settings.
    premission: nmc.nuggetmc
    usage: /nuggetmc
    aliases: [nmc]
  rank:
    description: Manually assigns ranks to players.
    permission: nmc.rank
    usage: /rank <player> <rank>
permissions:
  nmc.*:
    description: Blank description.
    children:
      nmc.debug: true
      nmc.ghead: true
      nmc.head: true
      nmc.ic: true
      nmc.nuggetmc: true
      nmc.rank: true
  nmc.debug:
    description: A command used to inject code when debugging.
    default: op
  nmc.ghead:
    description: Gives a player a Golden Head.
    default: op
  nmc.head:
    description: Gives a player a player's head.
    default: op
  nmc.ic:
    description: A developer tool to serialize player inventories.
    default: op
  nmc.nuggetmc:
    description: The plugin-hook configuration settings.
    default: op
  nmc.rank:
    description: Manually assigns ranks to players.
    default: op