enabled:
  announcements: true
  heads-gheads: true
  playertracker: true
join-msg:
- "&7--------------------------------------"
- ""
- "&e              Welcome to &6&lNuggetMC&r&e!"
- "&7          Discord: &9discord.gg/H6P8JT2"
- ""
- "&7--------------------------------------"
levelup-msg:
- "&2--------------------------------------"
- ""
- "&e                   &kX&r&e LEVEL UP &kX"
- "&2                 You are &eLevel <level>&2!"
- ""
- "&2--------------------------------------"
autorespawn-ticks: 12