non-default-worlds:
- main
non-default-worlds-nether:
- nether
non-default-worlds-the-end:
- end
uhckit-worlds:
- main
- nether
- end
spawn:
  world: main
  coordinates:
    x: 0.5
    y: 223
    z: 0.5
  region:
    pos1:
      x: -296
      y: 140
      z: -214
    pos2:
      x: 99
      y: 500
      z: 489
  outer-distance: 10